### ISSUE TITLE
[Feature request] Stereo support

### ISSUE THREAD

**Issue by kiwijam** [ArborealAudio/STR-X-v1.1#2]
I love your amp and how efficient it is. It deserves more exposure!

I just wish it had stereo support!

Wouldn't be great just for guitars, but also instruments that are usually stereo. Like synths!

**Comment by ArborealAudio** [comment]
Thank you! I've been planning on adding this pretty soon actually, along with some other stuff...

**Comment by kiwijam** [comment]
Thank you so much! ❤️

**Comment by ArborealAudio** [comment]
Added stereo support in v1.2!
