### ISSUE TITLE
LV2 support.

### ISSUE THREAD

**Issue by pspbar** [ArborealAudio/STR-X-v1.1#4]
I can not find the LV2 format in the tarball, and compiling from sources  only builds CLAP and VST3, but the readme says there is LV2 support for linux.

**Comment by ArborealAudio** [comment]
My apologies! The reason it got removed was because it was actually causing the compiler to segfault. I forgot to remove it as a supported target on our website. You can compile an LV2 by adding it to the `JUCE_FORMATS` variable in the CMakeLists.txt.

For the time being, there won't be LV2 support until I figure out why it is segfaulting the compiler.

**Comment by pspbar** [comment]
thank you for your quick response. I did the clone, submodule init, and then edited de CMakelists.txt file, leaving the line as set(JUCE_FORMATS LV2), then cmake --build build --config Release. That yields some warnings:

`CMake Warning at modules/juce/extras/Build/CMake/JUCEUtils.cmake:981 (message):
  LV2URI should be well-formed with an 'http' prefix.  Check the LV2URI
  argument to juce_add_plugin.
Call Stack (most recent call first):
  modules/juce/extras/Build/CMake/JUCEUtils.cmake:1091 (_juce_set_plugin_target_properties)
  modules/juce/extras/Build/CMake/JUCEUtils.cmake:1229 (_juce_link_plugin_wrapper)
  modules/juce/extras/Build/CMake/JUCEUtils.cmake:1770 (_juce_configure_plugin_targets)
  CMakeLists.txt:36 (juce_add_plugin)
`

Then, cmake -Bbuild -DPRODUCTION_BUILD=1, without the --target, because I can't figure out what target  is. It builds ok. Copied the resulting build/STR-X_artefacts/Release/LV2/STR-X.lv2/ to my ~/.lv2 dir. But it does not work. Ardour see the plugin but can not launch it. With jalv I get this errors:

`lv2ls|grep  STR
file:///plugins/STR_X
`

`pw-jack jalv.gtk3 file:///plugins/STR_X
Plugin:       file:///plugins/STR_X
UI:           file:///plugins/STR_X:UI
JACK Name:    STR-X
Sample rate:  48000 Hz
Block length: 1024 frames
MIDI buffers: 32768 bytes
Comm buffers: 148352 bytes
Update rate:  60,0 Hz
Scale factor: 1,0
lilv_plugin_instantiate(): error: No plugin <file:///plugins/STR_X> in <file:///home/user/.lv2/STR-X.lv2/libSTR-X.so>
error: Failed to instantiate plugin`

**Comment by ArborealAudio** [comment]
So the step `-Bbuild -DPRODUCTION_BUILD=1` comes first, then you run `cmake --build build --config Release --target STR-X_LV2`. Is that what you meant to say?

Regarding the warning, that's not really a big deal, an LV2 plugin just expects a URI to be associated with the plugin, so users can visit the source code if they wish. I can set that up to avoid the warning.

I can't really say why Ardour won't load the plugin, since it doesn't really explain in the error *why* it failed to instantiate it. Can you attach a debugger to Ardour and see if that outputs any additional information?

**Comment by pspbar** [comment]
> So the step `-Bbuild -DPRODUCTION_BUILD=1` comes first, then you run `cmake --build build --config Release --target STR-X_LV2`. Is that what you meant to say?

Builds both with the "--target STR-X_LV2", or without.  But both fail to run. 

> Regarding the warning, that's not really a big deal, an LV2 plugin just expects a URI to be associated with the plugin, so users can visit the source code if they wish. I can set that up to avoid the warning.

I think is more than a warning, because, loading the plugin with Carla, produce this error:
`Failed to load plugin
Could not find the requested plugin URI in the plugin library`

Also, lv2_validate  .lv2/STR-X.lv2/*.ttl produces a lot of errors like these:

```
error: Subject not in domain <http://usefulinc.com/ns/doap#Project>
       file:///plugins/STR_X
       http://usefulinc.com/ns/doap#maintainer
       b293
error: Subject not in domain <http://usefulinc.com/ns/doap#Project>
       file:///plugins/STR_X
       http://usefulinc.com/ns/doap#release
       b294
error: Object not in range <http://lv2plug.in/ns/lv2core#ExtensionData>

       file:///plugins/STR_X:UI
       http://lv2plug.in/ns/lv2core#extensionData 
```
> I can't really say why Ardour won't load the plugin, since it doesn't really explain in the error _why_ it failed to instantiate it. Can you attach a debugger to Ardour and see if that outputs any additional information?

Will try later, and be back with the result. 

Thank you very much for your help.

**Comment by ArborealAudio** [comment]
> Builds both with the "--target STR-X_LV2", or without. But both fail to run.

Right, it will build all targets if you don't specify a target. When you say they "fail to run" you mean none of the plugins can be loaded by a DAW?

Can you try building from the new `lv2` branch and let me know if it works any better?

**Comment by pspbar** [comment]
Indeed, it works. Thank you very much. I'm closing the issue.
